Add username K4anubhav
nlok5923/contribute pull request #7
Opened 2021-05-30 11:57 UTC by k4anubhav

add Name and what I learned today

2021-05-30 13:24 UTC, nlok5923 requested changes
thanks for pr take a look over comments.

2021-05-30 13:24 UTC, nlok5923 commented on _post/k4anubhav.txt
> +What you learned today: how to contribute :)
please add name field here.

2021-05-30 15:11 UTC, k4anubhav commented
Added Name field in k4anubhav.txt

2021-05-30 15:12 UTC, k4anubhav commented on _post/k4anubhav.txt
> +What you learned today: how to contribute :)
Done

2021-05-31 03:18 UTC, nlok5923 approved these changes
LGTM !!

2021-05-31 03:18 UTC, merged